M_SECOND_PER_MINIUTE = 60
M_MINIUTE_PER_HOUR = 60
M_HOUR_PER_DAY = 24
M_MILSECOND_PER_SECOND = 1000

M_MILSECOND_PER_DAY = M_SECOND_PER_MINIUTE * M_MINIUTE_PER_HOUR * M_HOUR_PER_DAY * M_MILSECOND_PER_SECOND
